platform :ios, '8.0'
inhibit_all_warnings!

pod 'Canvas', '~> 0.1.1'
pod 'libHN', '~> 2.0.0'
pod 'TPKeyboardAvoiding', '~> 1.2.3'
pod 'ACSimpleKeychain', '~> 0.0.1'
pod 'SimpleAudioPlayer', '~> 0.1.2'
